W7D3/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session
  resources :bands do 
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new,:index]
end

W7D3/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :band_id, presence: :true, uniqueness: :true
  validates :title, :year, presence: :true 

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band
end

W7D3/music_app/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

W7D3/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  attr_reader :password
  validates :email, presence: :true, uniqueness: :true
  validates :session_token, presence: :true
  validates :password_digest, presence: :true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else  
      nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

W7D3/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
        
    end

end

W7D3/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def log_out
    if logged_in?
      current_user.reset_session_token!
      session[:session_token] = nil
      @current_user = nil
    end
  end

end

W7D3/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    def new
        @band = Band.new
        render :new
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            redirect_to band_url(@band)
        else
            render :new
        end
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def index
        @bands = Band.all
        render :index
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end
    
    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to band_url(@band)
        else
            render :edit
        end

    end

    def destroy
        band = Band.find(params[:id])
        band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
end

W7D3/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

W7D3/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(params.require(:user).permit(:email,:password))

        if @user.save
            login!(@user) #login method from app. controller
            redirect_to user_url(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
        render :show
    end
end

W7D3/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W7D3/music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D3/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W7D3/music_app/app/views/bands/_band.html.erb
<li><%= band.name %></li>

W7D3/music_app/app/views/bands/_form.html.erb
<% if type == :new %>
    <% action_url = bands_url %>
    <% submit_text = "Create Band" %>
<% elsif type == :edit %>
    <% action_url = band_url(@band) %>
    <% submit_text = "Update Band" %>
<% end %>

<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value=<%form_authenticity_token%>>

    <% if type == :edit %>
        <input type="hidden" name="_method" value="PATCH" >
    <% end %>

    <label>Band Name:
        <input type="text" name="band[name]">
    </label>

    <br>


    <input type="submit" value="<%= submit_text %>">
</form>

W7D3/music_app/app/views/bands/edit.html.erb
<h2>Edit a band</h2>

<%= render "form", {band: @band, type: :edit} %>

W7D3/music_app/app/views/bands/index.html.erb

<ul>
  <% @bands.each do |band| %>
    <a href="<%= band_url(band) %>"> <%= render "band", { band: band } %> </a> 
  <% end %>
</ul>

W7D3/music_app/app/views/bands/new.html.erb
<h2>Create a band</h2>

<%= render "form", {band: @band, type: :new} %>

W7D3/music_app/app/views/bands/show.html.erb
<%= render "band", { band: @band } %>

<a href="<%= bands_url %>">Show all bands</a>
<a href="<%= edit_band_url(@band) %>">Edit Band</a>

<form action="<%= band_url(@band) %>" method="POST">
    <input type="hidden" name="authenticity_token" value=<%form_authenticity_token%>>
    <input type="hidden" name="_method" value="DELETE">

    <input type="submit" value="Irrelevant">
</form>

W7D3/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="main-header">Music App</h1>

    <% if logged_in? %>
      <form action="/session" method="POST">
        <input type="hidden" name="authenticity_token" value=<%form_authenticity_token%>>
        <input type="hidden" name="_method" value="DELETE">

        <input type="submit" value="Sign Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign in</a>
      <a href="<%= new_user_url %>">Sign up</a>
    <% end %>
    <%= yield %>
  </body>
</html>

W7D3/music_app/app/views/users/new.html.erb
<h2>This is the sign-up page!</h2>

<form action="/users" method="POST">
    <input type="hidden" name="authenticity_token" value=<%form_authenticity_token%>>
    <label>Email:
        <input type="text" name="user[email]" value="<%= @user.email ? @user.email : "" %>">
    </label>

    <br>

    <label>Password:
        <input type="text" name="user[password]" value="">
    </label>

    <input type="submit" value="Sign Up">

</form>

W7D3/music_app/app/views/users/show.html.erb
<h2>Hello <%= @user.email %></h2>

<br>


<%# <form action="/session" method="POST">
  <input type="hidden" name="_method" value="DELETE">

  <input type="submit" value="Sign Out">
</form> %>
<%# moved to app.html %>