W7D5/rails_2_practice_skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do 
    resources :goals, only: [:create]
  end
  resource :session
  resources :goals, only: [:destroy]

end

W7D5/rails_2_practice_skeleton/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D5/rails_2_practice_skeleton/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  status     :boolean          not null
#  details    :string           not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Goal < ApplicationRecord
    validates :name, :details, presence: true

    belongs_to :user,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :User

end

W7D5/rails_2_practice_skeleton/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true

    attr_reader :password
    after_initialize :ensure_session_token

    #SPIRE

    def self.find_by_credentials(user, pass)
        user = User.find_by(username: user)

        if user && user.is_password?(pass)
            user
        else  
            nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    has_many :goals,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Goal
end

W7D5/rails_2_practice_skeleton/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #CRLLL
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end
end

W7D5/rails_2_practice_skeleton/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    before_action :require_logged_in, only: [:create, :destroy]

    def create
        @goal = Goal.new(goal_params)
        @goal.user_id = params[:user_id]

        if @goal.save   
            redirect_to user_url(params[:user_id])
        else
            flash[:errors] = @goal.errors.full_messages  
            redirect_to user_url(params[:user_id])
        end
    end

    def destroy
        goal = Goal.find_by(id: params[:id])
        if goal && goal.user_id == current_user.id
            goal.delete
            redirect_to users_url
        else
            redirect_to new_session_url
        end
    end

    private

    def goal_params 
        params.require(:goal).permit(:name,:details,:status)
    end
end

W7D5/rails_2_practice_skeleton/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username],
        params[:user][:password])

        if @user
            login(@user)
            redirect_to users_url
        else  
            flash.now[:errors] = ['Invalid username or password']
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

W7D5/rails_2_practice_skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:show, :index]


    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to users_url
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def index
        @users = User.all
        render :index
    end
    private 

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

W7D5/rails_2_practice_skeleton/app/helpers/goals_helper.rb
module GoalsHelper
end

W7D5/rails_2_practice_skeleton/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D5/rails_2_practice_skeleton/app/helpers/users_helper.rb
module UsersHelper
end

W7D5/rails_2_practice_skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User Goal App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action="<%= session_url(current_user.id) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>
    <% end %>
    <%= yield %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>
  </body>
</html>

W7D5/rails_2_practice_skeleton/app/views/users/index.html.erb
<h2>All Users</h2>


<ul>
    <% @users.each do |user| %>
        <li>
            <a href="<%= user_url(user) %>"><%= user.username %></a>
        </li>
    <% end %>
</ul>

W7D5/rails_2_practice_skeleton/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="/users" method="POST">

    <label>Username:
        <input type="text" name="user[username]" value="<%= @user ? @user.username : "" %>">
    </label>

    <label>Password:
        <input type="password" name="user[password]" value="">
    </label>


    <input type="submit" value="Sign Up">
</form>

W7D5/rails_2_practice_skeleton/app/views/users/show.html.erb
<h2>Hello! <%= @user.username %></h2>

<% @user.goals.each do |goal| %>
    <ul>
        <li><%= goal.name %></li>
        <li><%= goal.details %></li>
        <li>
        <%= goal.status ? 'Done' : '' %>
        </li>
    </ul>
    <form action="<%= goal_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete Goal">
    </form>
<% end %>


<label>Add a New Goal</label>
<form action="<%= user_goals_url(@user) %>" method="POST">
    <label>Name:
        <input type="text" name="goal[name]">
    </label>

    <label>Details:
        <input type="text" name="goal[details]">
    </label>

    <label>Status:</label>
    <label>true
        <input type="radio" name="goal[status]" value="<%= true %>">
    </label>
    <label>false
        <input type="radio" name="goal[status]" value="<%= false %>">
    </label>

    <input type="submit" value="Create Goal">
</form>